### ISSUE TITLE
UI: Anchor component children overflow parent container width

### ISSUE THREAD

**Issue by KananSu** [google/perfetto#1037]
### Issue Description:
Hi, Dear Perfetto Team.

I would like to report a minor issue with the Anchor component. When the children content of an Anchor component is excessively long, it tends to overflow its parent container's width.
![Image](https://github.com/user-attachments/assets/a62cf5ae-d198-406a-8126-eb046a22e9ce)

### Suggested Solution:
Adding the CSS property `max-width: 100%` to the Anchor component can help ensure that long content wraps correctly.
```css
.pf-anchor {
  display: inline-block;
  line-height: 1;
  max-width: 100%; /* Ensures content does not exceed parent container's width */
}
````

I would be happy to submit a PR to implement this change if it would be helpful. Please let me know if this approach sounds good to you.

Thank you for considering this suggestion and for your continued dedication to the project.
